version: '#{build}-{branch}'
skip_tags: true
configuration: Release
platform:
- x86
- x64
build:
  project: BadApp.sln
  parallel: true
  verbosity: minimal
test: off
artifacts:
- path: bin\BadApp-$(Platform).exe
- path: bin\BadApp-$(Platform).pdb
skip_commits:
  files:
    - docs/*
    - '**/*.html'
deploy:
- provider: GitHub
  auth_token:
    secure: 0gpitdjlZDBJPr6BhWbZbRNV84AkN02IihwOxRS9+xiD63gvLyJV1NgOuL/kZ+y1
  draft: true
  on:
    APPVEYOR_REPO_TAG: true
