version: '#{build}-{branch}'
configuration: Release
platform:
- x86
- x64
build:
  project: BadApp.sln
  parallel: true
  verbosity: minimal
after_build:
  cmd:
    7z a BadApp-%PLATFORM%.zip %APPVEYOR_BUILD_FOLDER%\bin\BadApp-%PLATFORM%.exe %APPVEYOR_BUILD_FOLDER%\bin\BadApp-%PLATFORM%.pdb
test: off
artifacts:
- path: BadApp-$(platform).zip
  name: BadApp-$(platform)
skip_commits:
  files:
    - docs/*
    - '**/*.html'
deploy:
- provider: GitHub
  auth_token:
    secure: 0gpitdjlZDBJPr6BhWbZbRNV84AkN02IihwOxRS9+xiD63gvLyJV1NgOuL/kZ+y1
  draft: true
  on:
    APPVEYOR_REPO_TAG: true
